package com.om.blank.trade.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class userExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table euc_user
     *
     * @mbg.generated Wed Jan 10 23:23:47 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table euc_user
     *
     * @mbg.generated Wed Jan 10 23:23:47 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table euc_user
     *
     * @mbg.generated Wed Jan 10 23:23:47 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated Wed Jan 10 23:23:47 CST 2018
     */
    public userExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated Wed Jan 10 23:23:47 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated Wed Jan 10 23:23:47 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated Wed Jan 10 23:23:47 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated Wed Jan 10 23:23:47 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated Wed Jan 10 23:23:47 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated Wed Jan 10 23:23:47 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated Wed Jan 10 23:23:47 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated Wed Jan 10 23:23:47 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated Wed Jan 10 23:23:47 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated Wed Jan 10 23:23:47 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table euc_user
     *
     * @mbg.generated Wed Jan 10 23:23:47 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUser_idIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUser_idIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUser_idEqualTo(Long value) {
            addCriterion("user_id =", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotEqualTo(Long value) {
            addCriterion("user_id <>", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThan(Long value) {
            addCriterion("user_id >", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idGreaterThanOrEqualTo(Long value) {
            addCriterion("user_id >=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThan(Long value) {
            addCriterion("user_id <", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idLessThanOrEqualTo(Long value) {
            addCriterion("user_id <=", value, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idIn(List<Long> values) {
            addCriterion("user_id in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotIn(List<Long> values) {
            addCriterion("user_id not in", values, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idBetween(Long value1, Long value2) {
            addCriterion("user_id between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andUser_idNotBetween(Long value1, Long value2) {
            addCriterion("user_id not between", value1, value2, "user_id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idIsNull() {
            addCriterion("enterprise_id is null");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idIsNotNull() {
            addCriterion("enterprise_id is not null");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idEqualTo(Long value) {
            addCriterion("enterprise_id =", value, "enterprise_id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idNotEqualTo(Long value) {
            addCriterion("enterprise_id <>", value, "enterprise_id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idGreaterThan(Long value) {
            addCriterion("enterprise_id >", value, "enterprise_id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idGreaterThanOrEqualTo(Long value) {
            addCriterion("enterprise_id >=", value, "enterprise_id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idLessThan(Long value) {
            addCriterion("enterprise_id <", value, "enterprise_id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idLessThanOrEqualTo(Long value) {
            addCriterion("enterprise_id <=", value, "enterprise_id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idIn(List<Long> values) {
            addCriterion("enterprise_id in", values, "enterprise_id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idNotIn(List<Long> values) {
            addCriterion("enterprise_id not in", values, "enterprise_id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idBetween(Long value1, Long value2) {
            addCriterion("enterprise_id between", value1, value2, "enterprise_id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idNotBetween(Long value1, Long value2) {
            addCriterion("enterprise_id not between", value1, value2, "enterprise_id");
            return (Criteria) this;
        }

        public Criteria andAccountIsNull() {
            addCriterion("account is null");
            return (Criteria) this;
        }

        public Criteria andAccountIsNotNull() {
            addCriterion("account is not null");
            return (Criteria) this;
        }

        public Criteria andAccountEqualTo(String value) {
            addCriterion("account =", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotEqualTo(String value) {
            addCriterion("account <>", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThan(String value) {
            addCriterion("account >", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountGreaterThanOrEqualTo(String value) {
            addCriterion("account >=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThan(String value) {
            addCriterion("account <", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLessThanOrEqualTo(String value) {
            addCriterion("account <=", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountLike(String value) {
            addCriterion("account like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotLike(String value) {
            addCriterion("account not like", value, "account");
            return (Criteria) this;
        }

        public Criteria andAccountIn(List<String> values) {
            addCriterion("account in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotIn(List<String> values) {
            addCriterion("account not in", values, "account");
            return (Criteria) this;
        }

        public Criteria andAccountBetween(String value1, String value2) {
            addCriterion("account between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andAccountNotBetween(String value1, String value2) {
            addCriterion("account not between", value1, value2, "account");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andDepartment_idIsNull() {
            addCriterion("department_id is null");
            return (Criteria) this;
        }

        public Criteria andDepartment_idIsNotNull() {
            addCriterion("department_id is not null");
            return (Criteria) this;
        }

        public Criteria andDepartment_idEqualTo(Long value) {
            addCriterion("department_id =", value, "department_id");
            return (Criteria) this;
        }

        public Criteria andDepartment_idNotEqualTo(Long value) {
            addCriterion("department_id <>", value, "department_id");
            return (Criteria) this;
        }

        public Criteria andDepartment_idGreaterThan(Long value) {
            addCriterion("department_id >", value, "department_id");
            return (Criteria) this;
        }

        public Criteria andDepartment_idGreaterThanOrEqualTo(Long value) {
            addCriterion("department_id >=", value, "department_id");
            return (Criteria) this;
        }

        public Criteria andDepartment_idLessThan(Long value) {
            addCriterion("department_id <", value, "department_id");
            return (Criteria) this;
        }

        public Criteria andDepartment_idLessThanOrEqualTo(Long value) {
            addCriterion("department_id <=", value, "department_id");
            return (Criteria) this;
        }

        public Criteria andDepartment_idIn(List<Long> values) {
            addCriterion("department_id in", values, "department_id");
            return (Criteria) this;
        }

        public Criteria andDepartment_idNotIn(List<Long> values) {
            addCriterion("department_id not in", values, "department_id");
            return (Criteria) this;
        }

        public Criteria andDepartment_idBetween(Long value1, Long value2) {
            addCriterion("department_id between", value1, value2, "department_id");
            return (Criteria) this;
        }

        public Criteria andDepartment_idNotBetween(Long value1, Long value2) {
            addCriterion("department_id not between", value1, value2, "department_id");
            return (Criteria) this;
        }

        public Criteria andDepartment_nameIsNull() {
            addCriterion("department_name is null");
            return (Criteria) this;
        }

        public Criteria andDepartment_nameIsNotNull() {
            addCriterion("department_name is not null");
            return (Criteria) this;
        }

        public Criteria andDepartment_nameEqualTo(String value) {
            addCriterion("department_name =", value, "department_name");
            return (Criteria) this;
        }

        public Criteria andDepartment_nameNotEqualTo(String value) {
            addCriterion("department_name <>", value, "department_name");
            return (Criteria) this;
        }

        public Criteria andDepartment_nameGreaterThan(String value) {
            addCriterion("department_name >", value, "department_name");
            return (Criteria) this;
        }

        public Criteria andDepartment_nameGreaterThanOrEqualTo(String value) {
            addCriterion("department_name >=", value, "department_name");
            return (Criteria) this;
        }

        public Criteria andDepartment_nameLessThan(String value) {
            addCriterion("department_name <", value, "department_name");
            return (Criteria) this;
        }

        public Criteria andDepartment_nameLessThanOrEqualTo(String value) {
            addCriterion("department_name <=", value, "department_name");
            return (Criteria) this;
        }

        public Criteria andDepartment_nameLike(String value) {
            addCriterion("department_name like", value, "department_name");
            return (Criteria) this;
        }

        public Criteria andDepartment_nameNotLike(String value) {
            addCriterion("department_name not like", value, "department_name");
            return (Criteria) this;
        }

        public Criteria andDepartment_nameIn(List<String> values) {
            addCriterion("department_name in", values, "department_name");
            return (Criteria) this;
        }

        public Criteria andDepartment_nameNotIn(List<String> values) {
            addCriterion("department_name not in", values, "department_name");
            return (Criteria) this;
        }

        public Criteria andDepartment_nameBetween(String value1, String value2) {
            addCriterion("department_name between", value1, value2, "department_name");
            return (Criteria) this;
        }

        public Criteria andDepartment_nameNotBetween(String value1, String value2) {
            addCriterion("department_name not between", value1, value2, "department_name");
            return (Criteria) this;
        }

        public Criteria andOrganization_idIsNull() {
            addCriterion("organization_id is null");
            return (Criteria) this;
        }

        public Criteria andOrganization_idIsNotNull() {
            addCriterion("organization_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrganization_idEqualTo(Long value) {
            addCriterion("organization_id =", value, "organization_id");
            return (Criteria) this;
        }

        public Criteria andOrganization_idNotEqualTo(Long value) {
            addCriterion("organization_id <>", value, "organization_id");
            return (Criteria) this;
        }

        public Criteria andOrganization_idGreaterThan(Long value) {
            addCriterion("organization_id >", value, "organization_id");
            return (Criteria) this;
        }

        public Criteria andOrganization_idGreaterThanOrEqualTo(Long value) {
            addCriterion("organization_id >=", value, "organization_id");
            return (Criteria) this;
        }

        public Criteria andOrganization_idLessThan(Long value) {
            addCriterion("organization_id <", value, "organization_id");
            return (Criteria) this;
        }

        public Criteria andOrganization_idLessThanOrEqualTo(Long value) {
            addCriterion("organization_id <=", value, "organization_id");
            return (Criteria) this;
        }

        public Criteria andOrganization_idIn(List<Long> values) {
            addCriterion("organization_id in", values, "organization_id");
            return (Criteria) this;
        }

        public Criteria andOrganization_idNotIn(List<Long> values) {
            addCriterion("organization_id not in", values, "organization_id");
            return (Criteria) this;
        }

        public Criteria andOrganization_idBetween(Long value1, Long value2) {
            addCriterion("organization_id between", value1, value2, "organization_id");
            return (Criteria) this;
        }

        public Criteria andOrganization_idNotBetween(Long value1, Long value2) {
            addCriterion("organization_id not between", value1, value2, "organization_id");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameIsNull() {
            addCriterion("organization_name is null");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameIsNotNull() {
            addCriterion("organization_name is not null");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameEqualTo(String value) {
            addCriterion("organization_name =", value, "organization_name");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameNotEqualTo(String value) {
            addCriterion("organization_name <>", value, "organization_name");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameGreaterThan(String value) {
            addCriterion("organization_name >", value, "organization_name");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameGreaterThanOrEqualTo(String value) {
            addCriterion("organization_name >=", value, "organization_name");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameLessThan(String value) {
            addCriterion("organization_name <", value, "organization_name");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameLessThanOrEqualTo(String value) {
            addCriterion("organization_name <=", value, "organization_name");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameLike(String value) {
            addCriterion("organization_name like", value, "organization_name");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameNotLike(String value) {
            addCriterion("organization_name not like", value, "organization_name");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameIn(List<String> values) {
            addCriterion("organization_name in", values, "organization_name");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameNotIn(List<String> values) {
            addCriterion("organization_name not in", values, "organization_name");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameBetween(String value1, String value2) {
            addCriterion("organization_name between", value1, value2, "organization_name");
            return (Criteria) this;
        }

        public Criteria andOrganization_nameNotBetween(String value1, String value2) {
            addCriterion("organization_name not between", value1, value2, "organization_name");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andTelephoneIsNull() {
            addCriterion("telephone is null");
            return (Criteria) this;
        }

        public Criteria andTelephoneIsNotNull() {
            addCriterion("telephone is not null");
            return (Criteria) this;
        }

        public Criteria andTelephoneEqualTo(String value) {
            addCriterion("telephone =", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotEqualTo(String value) {
            addCriterion("telephone <>", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneGreaterThan(String value) {
            addCriterion("telephone >", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneGreaterThanOrEqualTo(String value) {
            addCriterion("telephone >=", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneLessThan(String value) {
            addCriterion("telephone <", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneLessThanOrEqualTo(String value) {
            addCriterion("telephone <=", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneLike(String value) {
            addCriterion("telephone like", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotLike(String value) {
            addCriterion("telephone not like", value, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneIn(List<String> values) {
            addCriterion("telephone in", values, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotIn(List<String> values) {
            addCriterion("telephone not in", values, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneBetween(String value1, String value2) {
            addCriterion("telephone between", value1, value2, "telephone");
            return (Criteria) this;
        }

        public Criteria andTelephoneNotBetween(String value1, String value2) {
            addCriterion("telephone not between", value1, value2, "telephone");
            return (Criteria) this;
        }

        public Criteria andIs_driverIsNull() {
            addCriterion("is_driver is null");
            return (Criteria) this;
        }

        public Criteria andIs_driverIsNotNull() {
            addCriterion("is_driver is not null");
            return (Criteria) this;
        }

        public Criteria andIs_driverEqualTo(String value) {
            addCriterion("is_driver =", value, "is_driver");
            return (Criteria) this;
        }

        public Criteria andIs_driverNotEqualTo(String value) {
            addCriterion("is_driver <>", value, "is_driver");
            return (Criteria) this;
        }

        public Criteria andIs_driverGreaterThan(String value) {
            addCriterion("is_driver >", value, "is_driver");
            return (Criteria) this;
        }

        public Criteria andIs_driverGreaterThanOrEqualTo(String value) {
            addCriterion("is_driver >=", value, "is_driver");
            return (Criteria) this;
        }

        public Criteria andIs_driverLessThan(String value) {
            addCriterion("is_driver <", value, "is_driver");
            return (Criteria) this;
        }

        public Criteria andIs_driverLessThanOrEqualTo(String value) {
            addCriterion("is_driver <=", value, "is_driver");
            return (Criteria) this;
        }

        public Criteria andIs_driverLike(String value) {
            addCriterion("is_driver like", value, "is_driver");
            return (Criteria) this;
        }

        public Criteria andIs_driverNotLike(String value) {
            addCriterion("is_driver not like", value, "is_driver");
            return (Criteria) this;
        }

        public Criteria andIs_driverIn(List<String> values) {
            addCriterion("is_driver in", values, "is_driver");
            return (Criteria) this;
        }

        public Criteria andIs_driverNotIn(List<String> values) {
            addCriterion("is_driver not in", values, "is_driver");
            return (Criteria) this;
        }

        public Criteria andIs_driverBetween(String value1, String value2) {
            addCriterion("is_driver between", value1, value2, "is_driver");
            return (Criteria) this;
        }

        public Criteria andIs_driverNotBetween(String value1, String value2) {
            addCriterion("is_driver not between", value1, value2, "is_driver");
            return (Criteria) this;
        }

        public Criteria andIdentity_numberIsNull() {
            addCriterion("Identity_number is null");
            return (Criteria) this;
        }

        public Criteria andIdentity_numberIsNotNull() {
            addCriterion("Identity_number is not null");
            return (Criteria) this;
        }

        public Criteria andIdentity_numberEqualTo(String value) {
            addCriterion("Identity_number =", value, "identity_number");
            return (Criteria) this;
        }

        public Criteria andIdentity_numberNotEqualTo(String value) {
            addCriterion("Identity_number <>", value, "identity_number");
            return (Criteria) this;
        }

        public Criteria andIdentity_numberGreaterThan(String value) {
            addCriterion("Identity_number >", value, "identity_number");
            return (Criteria) this;
        }

        public Criteria andIdentity_numberGreaterThanOrEqualTo(String value) {
            addCriterion("Identity_number >=", value, "identity_number");
            return (Criteria) this;
        }

        public Criteria andIdentity_numberLessThan(String value) {
            addCriterion("Identity_number <", value, "identity_number");
            return (Criteria) this;
        }

        public Criteria andIdentity_numberLessThanOrEqualTo(String value) {
            addCriterion("Identity_number <=", value, "identity_number");
            return (Criteria) this;
        }

        public Criteria andIdentity_numberLike(String value) {
            addCriterion("Identity_number like", value, "identity_number");
            return (Criteria) this;
        }

        public Criteria andIdentity_numberNotLike(String value) {
            addCriterion("Identity_number not like", value, "identity_number");
            return (Criteria) this;
        }

        public Criteria andIdentity_numberIn(List<String> values) {
            addCriterion("Identity_number in", values, "identity_number");
            return (Criteria) this;
        }

        public Criteria andIdentity_numberNotIn(List<String> values) {
            addCriterion("Identity_number not in", values, "identity_number");
            return (Criteria) this;
        }

        public Criteria andIdentity_numberBetween(String value1, String value2) {
            addCriterion("Identity_number between", value1, value2, "identity_number");
            return (Criteria) this;
        }

        public Criteria andIdentity_numberNotBetween(String value1, String value2) {
            addCriterion("Identity_number not between", value1, value2, "identity_number");
            return (Criteria) this;
        }

        public Criteria andDirver_numIsNull() {
            addCriterion("dirver_num is null");
            return (Criteria) this;
        }

        public Criteria andDirver_numIsNotNull() {
            addCriterion("dirver_num is not null");
            return (Criteria) this;
        }

        public Criteria andDirver_numEqualTo(String value) {
            addCriterion("dirver_num =", value, "dirver_num");
            return (Criteria) this;
        }

        public Criteria andDirver_numNotEqualTo(String value) {
            addCriterion("dirver_num <>", value, "dirver_num");
            return (Criteria) this;
        }

        public Criteria andDirver_numGreaterThan(String value) {
            addCriterion("dirver_num >", value, "dirver_num");
            return (Criteria) this;
        }

        public Criteria andDirver_numGreaterThanOrEqualTo(String value) {
            addCriterion("dirver_num >=", value, "dirver_num");
            return (Criteria) this;
        }

        public Criteria andDirver_numLessThan(String value) {
            addCriterion("dirver_num <", value, "dirver_num");
            return (Criteria) this;
        }

        public Criteria andDirver_numLessThanOrEqualTo(String value) {
            addCriterion("dirver_num <=", value, "dirver_num");
            return (Criteria) this;
        }

        public Criteria andDirver_numLike(String value) {
            addCriterion("dirver_num like", value, "dirver_num");
            return (Criteria) this;
        }

        public Criteria andDirver_numNotLike(String value) {
            addCriterion("dirver_num not like", value, "dirver_num");
            return (Criteria) this;
        }

        public Criteria andDirver_numIn(List<String> values) {
            addCriterion("dirver_num in", values, "dirver_num");
            return (Criteria) this;
        }

        public Criteria andDirver_numNotIn(List<String> values) {
            addCriterion("dirver_num not in", values, "dirver_num");
            return (Criteria) this;
        }

        public Criteria andDirver_numBetween(String value1, String value2) {
            addCriterion("dirver_num between", value1, value2, "dirver_num");
            return (Criteria) this;
        }

        public Criteria andDirver_numNotBetween(String value1, String value2) {
            addCriterion("dirver_num not between", value1, value2, "dirver_num");
            return (Criteria) this;
        }

        public Criteria andDriving_end_timeIsNull() {
            addCriterion("driving_end_time is null");
            return (Criteria) this;
        }

        public Criteria andDriving_end_timeIsNotNull() {
            addCriterion("driving_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andDriving_end_timeEqualTo(Date value) {
            addCriterion("driving_end_time =", value, "driving_end_time");
            return (Criteria) this;
        }

        public Criteria andDriving_end_timeNotEqualTo(Date value) {
            addCriterion("driving_end_time <>", value, "driving_end_time");
            return (Criteria) this;
        }

        public Criteria andDriving_end_timeGreaterThan(Date value) {
            addCriterion("driving_end_time >", value, "driving_end_time");
            return (Criteria) this;
        }

        public Criteria andDriving_end_timeGreaterThanOrEqualTo(Date value) {
            addCriterion("driving_end_time >=", value, "driving_end_time");
            return (Criteria) this;
        }

        public Criteria andDriving_end_timeLessThan(Date value) {
            addCriterion("driving_end_time <", value, "driving_end_time");
            return (Criteria) this;
        }

        public Criteria andDriving_end_timeLessThanOrEqualTo(Date value) {
            addCriterion("driving_end_time <=", value, "driving_end_time");
            return (Criteria) this;
        }

        public Criteria andDriving_end_timeIn(List<Date> values) {
            addCriterion("driving_end_time in", values, "driving_end_time");
            return (Criteria) this;
        }

        public Criteria andDriving_end_timeNotIn(List<Date> values) {
            addCriterion("driving_end_time not in", values, "driving_end_time");
            return (Criteria) this;
        }

        public Criteria andDriving_end_timeBetween(Date value1, Date value2) {
            addCriterion("driving_end_time between", value1, value2, "driving_end_time");
            return (Criteria) this;
        }

        public Criteria andDriving_end_timeNotBetween(Date value1, Date value2) {
            addCriterion("driving_end_time not between", value1, value2, "driving_end_time");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(Integer value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(Integer value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(Integer value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(Integer value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(Integer value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(Integer value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<Integer> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<Integer> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(Integer value1, Integer value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(Integer value1, Integer value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andIs_adminIsNull() {
            addCriterion("is_admin is null");
            return (Criteria) this;
        }

        public Criteria andIs_adminIsNotNull() {
            addCriterion("is_admin is not null");
            return (Criteria) this;
        }

        public Criteria andIs_adminEqualTo(Integer value) {
            addCriterion("is_admin =", value, "is_admin");
            return (Criteria) this;
        }

        public Criteria andIs_adminNotEqualTo(Integer value) {
            addCriterion("is_admin <>", value, "is_admin");
            return (Criteria) this;
        }

        public Criteria andIs_adminGreaterThan(Integer value) {
            addCriterion("is_admin >", value, "is_admin");
            return (Criteria) this;
        }

        public Criteria andIs_adminGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_admin >=", value, "is_admin");
            return (Criteria) this;
        }

        public Criteria andIs_adminLessThan(Integer value) {
            addCriterion("is_admin <", value, "is_admin");
            return (Criteria) this;
        }

        public Criteria andIs_adminLessThanOrEqualTo(Integer value) {
            addCriterion("is_admin <=", value, "is_admin");
            return (Criteria) this;
        }

        public Criteria andIs_adminIn(List<Integer> values) {
            addCriterion("is_admin in", values, "is_admin");
            return (Criteria) this;
        }

        public Criteria andIs_adminNotIn(List<Integer> values) {
            addCriterion("is_admin not in", values, "is_admin");
            return (Criteria) this;
        }

        public Criteria andIs_adminBetween(Integer value1, Integer value2) {
            addCriterion("is_admin between", value1, value2, "is_admin");
            return (Criteria) this;
        }

        public Criteria andIs_adminNotBetween(Integer value1, Integer value2) {
            addCriterion("is_admin not between", value1, value2, "is_admin");
            return (Criteria) this;
        }

        public Criteria andIs_system_userIsNull() {
            addCriterion("is_system_user is null");
            return (Criteria) this;
        }

        public Criteria andIs_system_userIsNotNull() {
            addCriterion("is_system_user is not null");
            return (Criteria) this;
        }

        public Criteria andIs_system_userEqualTo(Integer value) {
            addCriterion("is_system_user =", value, "is_system_user");
            return (Criteria) this;
        }

        public Criteria andIs_system_userNotEqualTo(Integer value) {
            addCriterion("is_system_user <>", value, "is_system_user");
            return (Criteria) this;
        }

        public Criteria andIs_system_userGreaterThan(Integer value) {
            addCriterion("is_system_user >", value, "is_system_user");
            return (Criteria) this;
        }

        public Criteria andIs_system_userGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_system_user >=", value, "is_system_user");
            return (Criteria) this;
        }

        public Criteria andIs_system_userLessThan(Integer value) {
            addCriterion("is_system_user <", value, "is_system_user");
            return (Criteria) this;
        }

        public Criteria andIs_system_userLessThanOrEqualTo(Integer value) {
            addCriterion("is_system_user <=", value, "is_system_user");
            return (Criteria) this;
        }

        public Criteria andIs_system_userIn(List<Integer> values) {
            addCriterion("is_system_user in", values, "is_system_user");
            return (Criteria) this;
        }

        public Criteria andIs_system_userNotIn(List<Integer> values) {
            addCriterion("is_system_user not in", values, "is_system_user");
            return (Criteria) this;
        }

        public Criteria andIs_system_userBetween(Integer value1, Integer value2) {
            addCriterion("is_system_user between", value1, value2, "is_system_user");
            return (Criteria) this;
        }

        public Criteria andIs_system_userNotBetween(Integer value1, Integer value2) {
            addCriterion("is_system_user not between", value1, value2, "is_system_user");
            return (Criteria) this;
        }

        public Criteria andOwner_typeIsNull() {
            addCriterion("owner_type is null");
            return (Criteria) this;
        }

        public Criteria andOwner_typeIsNotNull() {
            addCriterion("owner_type is not null");
            return (Criteria) this;
        }

        public Criteria andOwner_typeEqualTo(Integer value) {
            addCriterion("owner_type =", value, "owner_type");
            return (Criteria) this;
        }

        public Criteria andOwner_typeNotEqualTo(Integer value) {
            addCriterion("owner_type <>", value, "owner_type");
            return (Criteria) this;
        }

        public Criteria andOwner_typeGreaterThan(Integer value) {
            addCriterion("owner_type >", value, "owner_type");
            return (Criteria) this;
        }

        public Criteria andOwner_typeGreaterThanOrEqualTo(Integer value) {
            addCriterion("owner_type >=", value, "owner_type");
            return (Criteria) this;
        }

        public Criteria andOwner_typeLessThan(Integer value) {
            addCriterion("owner_type <", value, "owner_type");
            return (Criteria) this;
        }

        public Criteria andOwner_typeLessThanOrEqualTo(Integer value) {
            addCriterion("owner_type <=", value, "owner_type");
            return (Criteria) this;
        }

        public Criteria andOwner_typeIn(List<Integer> values) {
            addCriterion("owner_type in", values, "owner_type");
            return (Criteria) this;
        }

        public Criteria andOwner_typeNotIn(List<Integer> values) {
            addCriterion("owner_type not in", values, "owner_type");
            return (Criteria) this;
        }

        public Criteria andOwner_typeBetween(Integer value1, Integer value2) {
            addCriterion("owner_type between", value1, value2, "owner_type");
            return (Criteria) this;
        }

        public Criteria andOwner_typeNotBetween(Integer value1, Integer value2) {
            addCriterion("owner_type not between", value1, value2, "owner_type");
            return (Criteria) this;
        }

        public Criteria andIs_platformIsNull() {
            addCriterion("is_platform is null");
            return (Criteria) this;
        }

        public Criteria andIs_platformIsNotNull() {
            addCriterion("is_platform is not null");
            return (Criteria) this;
        }

        public Criteria andIs_platformEqualTo(Integer value) {
            addCriterion("is_platform =", value, "is_platform");
            return (Criteria) this;
        }

        public Criteria andIs_platformNotEqualTo(Integer value) {
            addCriterion("is_platform <>", value, "is_platform");
            return (Criteria) this;
        }

        public Criteria andIs_platformGreaterThan(Integer value) {
            addCriterion("is_platform >", value, "is_platform");
            return (Criteria) this;
        }

        public Criteria andIs_platformGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_platform >=", value, "is_platform");
            return (Criteria) this;
        }

        public Criteria andIs_platformLessThan(Integer value) {
            addCriterion("is_platform <", value, "is_platform");
            return (Criteria) this;
        }

        public Criteria andIs_platformLessThanOrEqualTo(Integer value) {
            addCriterion("is_platform <=", value, "is_platform");
            return (Criteria) this;
        }

        public Criteria andIs_platformIn(List<Integer> values) {
            addCriterion("is_platform in", values, "is_platform");
            return (Criteria) this;
        }

        public Criteria andIs_platformNotIn(List<Integer> values) {
            addCriterion("is_platform not in", values, "is_platform");
            return (Criteria) this;
        }

        public Criteria andIs_platformBetween(Integer value1, Integer value2) {
            addCriterion("is_platform between", value1, value2, "is_platform");
            return (Criteria) this;
        }

        public Criteria andIs_platformNotBetween(Integer value1, Integer value2) {
            addCriterion("is_platform not between", value1, value2, "is_platform");
            return (Criteria) this;
        }

        public Criteria andCompany_nameIsNull() {
            addCriterion("company_name is null");
            return (Criteria) this;
        }

        public Criteria andCompany_nameIsNotNull() {
            addCriterion("company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompany_nameEqualTo(String value) {
            addCriterion("company_name =", value, "company_name");
            return (Criteria) this;
        }

        public Criteria andCompany_nameNotEqualTo(String value) {
            addCriterion("company_name <>", value, "company_name");
            return (Criteria) this;
        }

        public Criteria andCompany_nameGreaterThan(String value) {
            addCriterion("company_name >", value, "company_name");
            return (Criteria) this;
        }

        public Criteria andCompany_nameGreaterThanOrEqualTo(String value) {
            addCriterion("company_name >=", value, "company_name");
            return (Criteria) this;
        }

        public Criteria andCompany_nameLessThan(String value) {
            addCriterion("company_name <", value, "company_name");
            return (Criteria) this;
        }

        public Criteria andCompany_nameLessThanOrEqualTo(String value) {
            addCriterion("company_name <=", value, "company_name");
            return (Criteria) this;
        }

        public Criteria andCompany_nameLike(String value) {
            addCriterion("company_name like", value, "company_name");
            return (Criteria) this;
        }

        public Criteria andCompany_nameNotLike(String value) {
            addCriterion("company_name not like", value, "company_name");
            return (Criteria) this;
        }

        public Criteria andCompany_nameIn(List<String> values) {
            addCriterion("company_name in", values, "company_name");
            return (Criteria) this;
        }

        public Criteria andCompany_nameNotIn(List<String> values) {
            addCriterion("company_name not in", values, "company_name");
            return (Criteria) this;
        }

        public Criteria andCompany_nameBetween(String value1, String value2) {
            addCriterion("company_name between", value1, value2, "company_name");
            return (Criteria) this;
        }

        public Criteria andCompany_nameNotBetween(String value1, String value2) {
            addCriterion("company_name not between", value1, value2, "company_name");
            return (Criteria) this;
        }

        public Criteria andPositionIsNull() {
            addCriterion("position is null");
            return (Criteria) this;
        }

        public Criteria andPositionIsNotNull() {
            addCriterion("position is not null");
            return (Criteria) this;
        }

        public Criteria andPositionEqualTo(Integer value) {
            addCriterion("position =", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotEqualTo(Integer value) {
            addCriterion("position <>", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThan(Integer value) {
            addCriterion("position >", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThanOrEqualTo(Integer value) {
            addCriterion("position >=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThan(Integer value) {
            addCriterion("position <", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThanOrEqualTo(Integer value) {
            addCriterion("position <=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionIn(List<Integer> values) {
            addCriterion("position in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotIn(List<Integer> values) {
            addCriterion("position not in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionBetween(Integer value1, Integer value2) {
            addCriterion("position between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotBetween(Integer value1, Integer value2) {
            addCriterion("position not between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("created is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("created is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("created =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("created <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("created >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("created >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("created <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("created <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("created in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("created not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("created between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("created not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNull() {
            addCriterion("updated is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNotNull() {
            addCriterion("updated is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedEqualTo(Date value) {
            addCriterion("updated =", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotEqualTo(Date value) {
            addCriterion("updated <>", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThan(Date value) {
            addCriterion("updated >", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThanOrEqualTo(Date value) {
            addCriterion("updated >=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThan(Date value) {
            addCriterion("updated <", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThanOrEqualTo(Date value) {
            addCriterion("updated <=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedIn(List<Date> values) {
            addCriterion("updated in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotIn(List<Date> values) {
            addCriterion("updated not in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedBetween(Date value1, Date value2) {
            addCriterion("updated between", value1, value2, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotBetween(Date value1, Date value2) {
            addCriterion("updated not between", value1, value2, "updated");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Date value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Date value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Date value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Date value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Date value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Date value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Date> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Date> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Date value1, Date value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Date value1, Date value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table euc_user
     *
     * @mbg.generated do_not_delete_during_merge Wed Jan 10 23:23:47 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table euc_user
     *
     * @mbg.generated Wed Jan 10 23:23:47 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}