package com.om.blank.trade.mybatis.model;

import java.util.Date;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_department.department_id
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    private Long department_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_department.name
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_department.parent_department_id
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    private Long parent_department_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_department.enterprise_id
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    private Long enterprise_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_department.type
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_department.adapter_param
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    private String adapter_param;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_department.enterprise_code
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    private String enterprise_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_department.manufacturer_code
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    private String manufacturer_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_department.secret
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    private String secret;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_department.address
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_department.level_code
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    private String level_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_department.created
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_department.updated
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    private Date updated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_department.deleted
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    private Date deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_department.department_shortened
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    private String department_shortened;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_department.department_id
     *
     * @return the value of euc_department.department_id
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public Long getDepartment_id() {
        return department_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_department.department_id
     *
     * @param department_id the value for euc_department.department_id
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public void setDepartment_id(Long department_id) {
        this.department_id = department_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_department.name
     *
     * @return the value of euc_department.name
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_department.name
     *
     * @param name the value for euc_department.name
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_department.parent_department_id
     *
     * @return the value of euc_department.parent_department_id
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public Long getParent_department_id() {
        return parent_department_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_department.parent_department_id
     *
     * @param parent_department_id the value for euc_department.parent_department_id
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public void setParent_department_id(Long parent_department_id) {
        this.parent_department_id = parent_department_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_department.enterprise_id
     *
     * @return the value of euc_department.enterprise_id
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public Long getEnterprise_id() {
        return enterprise_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_department.enterprise_id
     *
     * @param enterprise_id the value for euc_department.enterprise_id
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public void setEnterprise_id(Long enterprise_id) {
        this.enterprise_id = enterprise_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_department.type
     *
     * @return the value of euc_department.type
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_department.type
     *
     * @param type the value for euc_department.type
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_department.adapter_param
     *
     * @return the value of euc_department.adapter_param
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public String getAdapter_param() {
        return adapter_param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_department.adapter_param
     *
     * @param adapter_param the value for euc_department.adapter_param
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public void setAdapter_param(String adapter_param) {
        this.adapter_param = adapter_param == null ? null : adapter_param.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_department.enterprise_code
     *
     * @return the value of euc_department.enterprise_code
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public String getEnterprise_code() {
        return enterprise_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_department.enterprise_code
     *
     * @param enterprise_code the value for euc_department.enterprise_code
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public void setEnterprise_code(String enterprise_code) {
        this.enterprise_code = enterprise_code == null ? null : enterprise_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_department.manufacturer_code
     *
     * @return the value of euc_department.manufacturer_code
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public String getManufacturer_code() {
        return manufacturer_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_department.manufacturer_code
     *
     * @param manufacturer_code the value for euc_department.manufacturer_code
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public void setManufacturer_code(String manufacturer_code) {
        this.manufacturer_code = manufacturer_code == null ? null : manufacturer_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_department.secret
     *
     * @return the value of euc_department.secret
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public String getSecret() {
        return secret;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_department.secret
     *
     * @param secret the value for euc_department.secret
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public void setSecret(String secret) {
        this.secret = secret == null ? null : secret.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_department.address
     *
     * @return the value of euc_department.address
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_department.address
     *
     * @param address the value for euc_department.address
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_department.level_code
     *
     * @return the value of euc_department.level_code
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public String getLevel_code() {
        return level_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_department.level_code
     *
     * @param level_code the value for euc_department.level_code
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public void setLevel_code(String level_code) {
        this.level_code = level_code == null ? null : level_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_department.created
     *
     * @return the value of euc_department.created
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_department.created
     *
     * @param created the value for euc_department.created
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_department.updated
     *
     * @return the value of euc_department.updated
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_department.updated
     *
     * @param updated the value for euc_department.updated
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_department.deleted
     *
     * @return the value of euc_department.deleted
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public Date getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_department.deleted
     *
     * @param deleted the value for euc_department.deleted
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public void setDeleted(Date deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_department.department_shortened
     *
     * @return the value of euc_department.department_shortened
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public String getDepartment_shortened() {
        return department_shortened;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_department.department_shortened
     *
     * @param department_shortened the value for euc_department.department_shortened
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public void setDepartment_shortened(String department_shortened) {
        this.department_shortened = department_shortened == null ? null : department_shortened.trim();
    }
}