package com.om.blank.trade.mybatis.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DepartmentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table euc_department
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table euc_department
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table euc_department
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_department
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public DepartmentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_department
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_department
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_department
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_department
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_department
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_department
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_department
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_department
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_department
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_department
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table euc_department
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDepartment_idIsNull() {
            addCriterion("department_id is null");
            return (Criteria) this;
        }

        public Criteria andDepartment_idIsNotNull() {
            addCriterion("department_id is not null");
            return (Criteria) this;
        }

        public Criteria andDepartment_idEqualTo(Long value) {
            addCriterion("department_id =", value, "department_id");
            return (Criteria) this;
        }

        public Criteria andDepartment_idNotEqualTo(Long value) {
            addCriterion("department_id <>", value, "department_id");
            return (Criteria) this;
        }

        public Criteria andDepartment_idGreaterThan(Long value) {
            addCriterion("department_id >", value, "department_id");
            return (Criteria) this;
        }

        public Criteria andDepartment_idGreaterThanOrEqualTo(Long value) {
            addCriterion("department_id >=", value, "department_id");
            return (Criteria) this;
        }

        public Criteria andDepartment_idLessThan(Long value) {
            addCriterion("department_id <", value, "department_id");
            return (Criteria) this;
        }

        public Criteria andDepartment_idLessThanOrEqualTo(Long value) {
            addCriterion("department_id <=", value, "department_id");
            return (Criteria) this;
        }

        public Criteria andDepartment_idIn(List<Long> values) {
            addCriterion("department_id in", values, "department_id");
            return (Criteria) this;
        }

        public Criteria andDepartment_idNotIn(List<Long> values) {
            addCriterion("department_id not in", values, "department_id");
            return (Criteria) this;
        }

        public Criteria andDepartment_idBetween(Long value1, Long value2) {
            addCriterion("department_id between", value1, value2, "department_id");
            return (Criteria) this;
        }

        public Criteria andDepartment_idNotBetween(Long value1, Long value2) {
            addCriterion("department_id not between", value1, value2, "department_id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andParent_department_idIsNull() {
            addCriterion("parent_department_id is null");
            return (Criteria) this;
        }

        public Criteria andParent_department_idIsNotNull() {
            addCriterion("parent_department_id is not null");
            return (Criteria) this;
        }

        public Criteria andParent_department_idEqualTo(Long value) {
            addCriterion("parent_department_id =", value, "parent_department_id");
            return (Criteria) this;
        }

        public Criteria andParent_department_idNotEqualTo(Long value) {
            addCriterion("parent_department_id <>", value, "parent_department_id");
            return (Criteria) this;
        }

        public Criteria andParent_department_idGreaterThan(Long value) {
            addCriterion("parent_department_id >", value, "parent_department_id");
            return (Criteria) this;
        }

        public Criteria andParent_department_idGreaterThanOrEqualTo(Long value) {
            addCriterion("parent_department_id >=", value, "parent_department_id");
            return (Criteria) this;
        }

        public Criteria andParent_department_idLessThan(Long value) {
            addCriterion("parent_department_id <", value, "parent_department_id");
            return (Criteria) this;
        }

        public Criteria andParent_department_idLessThanOrEqualTo(Long value) {
            addCriterion("parent_department_id <=", value, "parent_department_id");
            return (Criteria) this;
        }

        public Criteria andParent_department_idIn(List<Long> values) {
            addCriterion("parent_department_id in", values, "parent_department_id");
            return (Criteria) this;
        }

        public Criteria andParent_department_idNotIn(List<Long> values) {
            addCriterion("parent_department_id not in", values, "parent_department_id");
            return (Criteria) this;
        }

        public Criteria andParent_department_idBetween(Long value1, Long value2) {
            addCriterion("parent_department_id between", value1, value2, "parent_department_id");
            return (Criteria) this;
        }

        public Criteria andParent_department_idNotBetween(Long value1, Long value2) {
            addCriterion("parent_department_id not between", value1, value2, "parent_department_id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idIsNull() {
            addCriterion("enterprise_id is null");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idIsNotNull() {
            addCriterion("enterprise_id is not null");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idEqualTo(Long value) {
            addCriterion("enterprise_id =", value, "enterprise_id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idNotEqualTo(Long value) {
            addCriterion("enterprise_id <>", value, "enterprise_id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idGreaterThan(Long value) {
            addCriterion("enterprise_id >", value, "enterprise_id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idGreaterThanOrEqualTo(Long value) {
            addCriterion("enterprise_id >=", value, "enterprise_id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idLessThan(Long value) {
            addCriterion("enterprise_id <", value, "enterprise_id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idLessThanOrEqualTo(Long value) {
            addCriterion("enterprise_id <=", value, "enterprise_id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idIn(List<Long> values) {
            addCriterion("enterprise_id in", values, "enterprise_id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idNotIn(List<Long> values) {
            addCriterion("enterprise_id not in", values, "enterprise_id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idBetween(Long value1, Long value2) {
            addCriterion("enterprise_id between", value1, value2, "enterprise_id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_idNotBetween(Long value1, Long value2) {
            addCriterion("enterprise_id not between", value1, value2, "enterprise_id");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andAdapter_paramIsNull() {
            addCriterion("adapter_param is null");
            return (Criteria) this;
        }

        public Criteria andAdapter_paramIsNotNull() {
            addCriterion("adapter_param is not null");
            return (Criteria) this;
        }

        public Criteria andAdapter_paramEqualTo(String value) {
            addCriterion("adapter_param =", value, "adapter_param");
            return (Criteria) this;
        }

        public Criteria andAdapter_paramNotEqualTo(String value) {
            addCriterion("adapter_param <>", value, "adapter_param");
            return (Criteria) this;
        }

        public Criteria andAdapter_paramGreaterThan(String value) {
            addCriterion("adapter_param >", value, "adapter_param");
            return (Criteria) this;
        }

        public Criteria andAdapter_paramGreaterThanOrEqualTo(String value) {
            addCriterion("adapter_param >=", value, "adapter_param");
            return (Criteria) this;
        }

        public Criteria andAdapter_paramLessThan(String value) {
            addCriterion("adapter_param <", value, "adapter_param");
            return (Criteria) this;
        }

        public Criteria andAdapter_paramLessThanOrEqualTo(String value) {
            addCriterion("adapter_param <=", value, "adapter_param");
            return (Criteria) this;
        }

        public Criteria andAdapter_paramLike(String value) {
            addCriterion("adapter_param like", value, "adapter_param");
            return (Criteria) this;
        }

        public Criteria andAdapter_paramNotLike(String value) {
            addCriterion("adapter_param not like", value, "adapter_param");
            return (Criteria) this;
        }

        public Criteria andAdapter_paramIn(List<String> values) {
            addCriterion("adapter_param in", values, "adapter_param");
            return (Criteria) this;
        }

        public Criteria andAdapter_paramNotIn(List<String> values) {
            addCriterion("adapter_param not in", values, "adapter_param");
            return (Criteria) this;
        }

        public Criteria andAdapter_paramBetween(String value1, String value2) {
            addCriterion("adapter_param between", value1, value2, "adapter_param");
            return (Criteria) this;
        }

        public Criteria andAdapter_paramNotBetween(String value1, String value2) {
            addCriterion("adapter_param not between", value1, value2, "adapter_param");
            return (Criteria) this;
        }

        public Criteria andEnterprise_codeIsNull() {
            addCriterion("enterprise_code is null");
            return (Criteria) this;
        }

        public Criteria andEnterprise_codeIsNotNull() {
            addCriterion("enterprise_code is not null");
            return (Criteria) this;
        }

        public Criteria andEnterprise_codeEqualTo(String value) {
            addCriterion("enterprise_code =", value, "enterprise_code");
            return (Criteria) this;
        }

        public Criteria andEnterprise_codeNotEqualTo(String value) {
            addCriterion("enterprise_code <>", value, "enterprise_code");
            return (Criteria) this;
        }

        public Criteria andEnterprise_codeGreaterThan(String value) {
            addCriterion("enterprise_code >", value, "enterprise_code");
            return (Criteria) this;
        }

        public Criteria andEnterprise_codeGreaterThanOrEqualTo(String value) {
            addCriterion("enterprise_code >=", value, "enterprise_code");
            return (Criteria) this;
        }

        public Criteria andEnterprise_codeLessThan(String value) {
            addCriterion("enterprise_code <", value, "enterprise_code");
            return (Criteria) this;
        }

        public Criteria andEnterprise_codeLessThanOrEqualTo(String value) {
            addCriterion("enterprise_code <=", value, "enterprise_code");
            return (Criteria) this;
        }

        public Criteria andEnterprise_codeLike(String value) {
            addCriterion("enterprise_code like", value, "enterprise_code");
            return (Criteria) this;
        }

        public Criteria andEnterprise_codeNotLike(String value) {
            addCriterion("enterprise_code not like", value, "enterprise_code");
            return (Criteria) this;
        }

        public Criteria andEnterprise_codeIn(List<String> values) {
            addCriterion("enterprise_code in", values, "enterprise_code");
            return (Criteria) this;
        }

        public Criteria andEnterprise_codeNotIn(List<String> values) {
            addCriterion("enterprise_code not in", values, "enterprise_code");
            return (Criteria) this;
        }

        public Criteria andEnterprise_codeBetween(String value1, String value2) {
            addCriterion("enterprise_code between", value1, value2, "enterprise_code");
            return (Criteria) this;
        }

        public Criteria andEnterprise_codeNotBetween(String value1, String value2) {
            addCriterion("enterprise_code not between", value1, value2, "enterprise_code");
            return (Criteria) this;
        }

        public Criteria andManufacturer_codeIsNull() {
            addCriterion("manufacturer_code is null");
            return (Criteria) this;
        }

        public Criteria andManufacturer_codeIsNotNull() {
            addCriterion("manufacturer_code is not null");
            return (Criteria) this;
        }

        public Criteria andManufacturer_codeEqualTo(String value) {
            addCriterion("manufacturer_code =", value, "manufacturer_code");
            return (Criteria) this;
        }

        public Criteria andManufacturer_codeNotEqualTo(String value) {
            addCriterion("manufacturer_code <>", value, "manufacturer_code");
            return (Criteria) this;
        }

        public Criteria andManufacturer_codeGreaterThan(String value) {
            addCriterion("manufacturer_code >", value, "manufacturer_code");
            return (Criteria) this;
        }

        public Criteria andManufacturer_codeGreaterThanOrEqualTo(String value) {
            addCriterion("manufacturer_code >=", value, "manufacturer_code");
            return (Criteria) this;
        }

        public Criteria andManufacturer_codeLessThan(String value) {
            addCriterion("manufacturer_code <", value, "manufacturer_code");
            return (Criteria) this;
        }

        public Criteria andManufacturer_codeLessThanOrEqualTo(String value) {
            addCriterion("manufacturer_code <=", value, "manufacturer_code");
            return (Criteria) this;
        }

        public Criteria andManufacturer_codeLike(String value) {
            addCriterion("manufacturer_code like", value, "manufacturer_code");
            return (Criteria) this;
        }

        public Criteria andManufacturer_codeNotLike(String value) {
            addCriterion("manufacturer_code not like", value, "manufacturer_code");
            return (Criteria) this;
        }

        public Criteria andManufacturer_codeIn(List<String> values) {
            addCriterion("manufacturer_code in", values, "manufacturer_code");
            return (Criteria) this;
        }

        public Criteria andManufacturer_codeNotIn(List<String> values) {
            addCriterion("manufacturer_code not in", values, "manufacturer_code");
            return (Criteria) this;
        }

        public Criteria andManufacturer_codeBetween(String value1, String value2) {
            addCriterion("manufacturer_code between", value1, value2, "manufacturer_code");
            return (Criteria) this;
        }

        public Criteria andManufacturer_codeNotBetween(String value1, String value2) {
            addCriterion("manufacturer_code not between", value1, value2, "manufacturer_code");
            return (Criteria) this;
        }

        public Criteria andSecretIsNull() {
            addCriterion("secret is null");
            return (Criteria) this;
        }

        public Criteria andSecretIsNotNull() {
            addCriterion("secret is not null");
            return (Criteria) this;
        }

        public Criteria andSecretEqualTo(String value) {
            addCriterion("secret =", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretNotEqualTo(String value) {
            addCriterion("secret <>", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretGreaterThan(String value) {
            addCriterion("secret >", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretGreaterThanOrEqualTo(String value) {
            addCriterion("secret >=", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretLessThan(String value) {
            addCriterion("secret <", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretLessThanOrEqualTo(String value) {
            addCriterion("secret <=", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretLike(String value) {
            addCriterion("secret like", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretNotLike(String value) {
            addCriterion("secret not like", value, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretIn(List<String> values) {
            addCriterion("secret in", values, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretNotIn(List<String> values) {
            addCriterion("secret not in", values, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretBetween(String value1, String value2) {
            addCriterion("secret between", value1, value2, "secret");
            return (Criteria) this;
        }

        public Criteria andSecretNotBetween(String value1, String value2) {
            addCriterion("secret not between", value1, value2, "secret");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andLevel_codeIsNull() {
            addCriterion("level_code is null");
            return (Criteria) this;
        }

        public Criteria andLevel_codeIsNotNull() {
            addCriterion("level_code is not null");
            return (Criteria) this;
        }

        public Criteria andLevel_codeEqualTo(String value) {
            addCriterion("level_code =", value, "level_code");
            return (Criteria) this;
        }

        public Criteria andLevel_codeNotEqualTo(String value) {
            addCriterion("level_code <>", value, "level_code");
            return (Criteria) this;
        }

        public Criteria andLevel_codeGreaterThan(String value) {
            addCriterion("level_code >", value, "level_code");
            return (Criteria) this;
        }

        public Criteria andLevel_codeGreaterThanOrEqualTo(String value) {
            addCriterion("level_code >=", value, "level_code");
            return (Criteria) this;
        }

        public Criteria andLevel_codeLessThan(String value) {
            addCriterion("level_code <", value, "level_code");
            return (Criteria) this;
        }

        public Criteria andLevel_codeLessThanOrEqualTo(String value) {
            addCriterion("level_code <=", value, "level_code");
            return (Criteria) this;
        }

        public Criteria andLevel_codeLike(String value) {
            addCriterion("level_code like", value, "level_code");
            return (Criteria) this;
        }

        public Criteria andLevel_codeNotLike(String value) {
            addCriterion("level_code not like", value, "level_code");
            return (Criteria) this;
        }

        public Criteria andLevel_codeIn(List<String> values) {
            addCriterion("level_code in", values, "level_code");
            return (Criteria) this;
        }

        public Criteria andLevel_codeNotIn(List<String> values) {
            addCriterion("level_code not in", values, "level_code");
            return (Criteria) this;
        }

        public Criteria andLevel_codeBetween(String value1, String value2) {
            addCriterion("level_code between", value1, value2, "level_code");
            return (Criteria) this;
        }

        public Criteria andLevel_codeNotBetween(String value1, String value2) {
            addCriterion("level_code not between", value1, value2, "level_code");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNull() {
            addCriterion("created is null");
            return (Criteria) this;
        }

        public Criteria andCreatedIsNotNull() {
            addCriterion("created is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedEqualTo(Date value) {
            addCriterion("created =", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotEqualTo(Date value) {
            addCriterion("created <>", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThan(Date value) {
            addCriterion("created >", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("created >=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThan(Date value) {
            addCriterion("created <", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedLessThanOrEqualTo(Date value) {
            addCriterion("created <=", value, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedIn(List<Date> values) {
            addCriterion("created in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotIn(List<Date> values) {
            addCriterion("created not in", values, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedBetween(Date value1, Date value2) {
            addCriterion("created between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andCreatedNotBetween(Date value1, Date value2) {
            addCriterion("created not between", value1, value2, "created");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNull() {
            addCriterion("updated is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedIsNotNull() {
            addCriterion("updated is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedEqualTo(Date value) {
            addCriterion("updated =", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotEqualTo(Date value) {
            addCriterion("updated <>", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThan(Date value) {
            addCriterion("updated >", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedGreaterThanOrEqualTo(Date value) {
            addCriterion("updated >=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThan(Date value) {
            addCriterion("updated <", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedLessThanOrEqualTo(Date value) {
            addCriterion("updated <=", value, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedIn(List<Date> values) {
            addCriterion("updated in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotIn(List<Date> values) {
            addCriterion("updated not in", values, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedBetween(Date value1, Date value2) {
            addCriterion("updated between", value1, value2, "updated");
            return (Criteria) this;
        }

        public Criteria andUpdatedNotBetween(Date value1, Date value2) {
            addCriterion("updated not between", value1, value2, "updated");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNull() {
            addCriterion("deleted is null");
            return (Criteria) this;
        }

        public Criteria andDeletedIsNotNull() {
            addCriterion("deleted is not null");
            return (Criteria) this;
        }

        public Criteria andDeletedEqualTo(Date value) {
            addCriterion("deleted =", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotEqualTo(Date value) {
            addCriterion("deleted <>", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThan(Date value) {
            addCriterion("deleted >", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedGreaterThanOrEqualTo(Date value) {
            addCriterion("deleted >=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThan(Date value) {
            addCriterion("deleted <", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedLessThanOrEqualTo(Date value) {
            addCriterion("deleted <=", value, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedIn(List<Date> values) {
            addCriterion("deleted in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotIn(List<Date> values) {
            addCriterion("deleted not in", values, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedBetween(Date value1, Date value2) {
            addCriterion("deleted between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDeletedNotBetween(Date value1, Date value2) {
            addCriterion("deleted not between", value1, value2, "deleted");
            return (Criteria) this;
        }

        public Criteria andDepartment_shortenedIsNull() {
            addCriterion("department_shortened is null");
            return (Criteria) this;
        }

        public Criteria andDepartment_shortenedIsNotNull() {
            addCriterion("department_shortened is not null");
            return (Criteria) this;
        }

        public Criteria andDepartment_shortenedEqualTo(String value) {
            addCriterion("department_shortened =", value, "department_shortened");
            return (Criteria) this;
        }

        public Criteria andDepartment_shortenedNotEqualTo(String value) {
            addCriterion("department_shortened <>", value, "department_shortened");
            return (Criteria) this;
        }

        public Criteria andDepartment_shortenedGreaterThan(String value) {
            addCriterion("department_shortened >", value, "department_shortened");
            return (Criteria) this;
        }

        public Criteria andDepartment_shortenedGreaterThanOrEqualTo(String value) {
            addCriterion("department_shortened >=", value, "department_shortened");
            return (Criteria) this;
        }

        public Criteria andDepartment_shortenedLessThan(String value) {
            addCriterion("department_shortened <", value, "department_shortened");
            return (Criteria) this;
        }

        public Criteria andDepartment_shortenedLessThanOrEqualTo(String value) {
            addCriterion("department_shortened <=", value, "department_shortened");
            return (Criteria) this;
        }

        public Criteria andDepartment_shortenedLike(String value) {
            addCriterion("department_shortened like", value, "department_shortened");
            return (Criteria) this;
        }

        public Criteria andDepartment_shortenedNotLike(String value) {
            addCriterion("department_shortened not like", value, "department_shortened");
            return (Criteria) this;
        }

        public Criteria andDepartment_shortenedIn(List<String> values) {
            addCriterion("department_shortened in", values, "department_shortened");
            return (Criteria) this;
        }

        public Criteria andDepartment_shortenedNotIn(List<String> values) {
            addCriterion("department_shortened not in", values, "department_shortened");
            return (Criteria) this;
        }

        public Criteria andDepartment_shortenedBetween(String value1, String value2) {
            addCriterion("department_shortened between", value1, value2, "department_shortened");
            return (Criteria) this;
        }

        public Criteria andDepartment_shortenedNotBetween(String value1, String value2) {
            addCriterion("department_shortened not between", value1, value2, "department_shortened");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table euc_department
     *
     * @mbg.generated do_not_delete_during_merge Sun Jan 21 18:20:00 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table euc_department
     *
     * @mbg.generated Sun Jan 21 18:20:00 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}