package com.om.blank.trade.mybatis.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.user_id
     *
     * @mbg.generated
     */
    private Long user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.enterprise_id
     *
     * @mbg.generated
     */
    private Long enterprise_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.account
     *
     * @mbg.generated
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.department_id
     *
     * @mbg.generated
     */
    private Long department_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.department_name
     *
     * @mbg.generated
     */
    private String department_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.organization_id
     *
     * @mbg.generated
     */
    private Long organization_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.organization_name
     *
     * @mbg.generated
     */
    private String organization_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.telephone
     *
     * @mbg.generated
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.is_driver
     *
     * @mbg.generated
     */
    private String is_driver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.Identity_number
     *
     * @mbg.generated
     */
    private String identity_number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.dirver_num
     *
     * @mbg.generated
     */
    private String dirver_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.driving_end_time
     *
     * @mbg.generated
     */
    private Date driving_end_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.is_admin
     *
     * @mbg.generated
     */
    private Integer is_admin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.is_system_user
     *
     * @mbg.generated
     */
    private Integer is_system_user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.owner_type
     *
     * @mbg.generated
     */
    private Integer owner_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.is_platform
     *
     * @mbg.generated
     */
    private Integer is_platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.company_name
     *
     * @mbg.generated
     */
    private String company_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.position
     *
     * @mbg.generated
     */
    private Integer position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.created
     *
     * @mbg.generated
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.updated
     *
     * @mbg.generated
     */
    private Date updated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.deleted
     *
     * @mbg.generated
     */
    private Date deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.user_id
     *
     * @return the value of euc_user.user_id
     *
     * @mbg.generated
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.user_id
     *
     * @param user_id the value for euc_user.user_id
     *
     * @mbg.generated
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.name
     *
     * @return the value of euc_user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.name
     *
     * @param name the value for euc_user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.enterprise_id
     *
     * @return the value of euc_user.enterprise_id
     *
     * @mbg.generated
     */
    public Long getEnterprise_id() {
        return enterprise_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.enterprise_id
     *
     * @param enterprise_id the value for euc_user.enterprise_id
     *
     * @mbg.generated
     */
    public void setEnterprise_id(Long enterprise_id) {
        this.enterprise_id = enterprise_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.account
     *
     * @return the value of euc_user.account
     *
     * @mbg.generated
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.account
     *
     * @param account the value for euc_user.account
     *
     * @mbg.generated
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.password
     *
     * @return the value of euc_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.password
     *
     * @param password the value for euc_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.department_id
     *
     * @return the value of euc_user.department_id
     *
     * @mbg.generated
     */
    public Long getDepartment_id() {
        return department_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.department_id
     *
     * @param department_id the value for euc_user.department_id
     *
     * @mbg.generated
     */
    public void setDepartment_id(Long department_id) {
        this.department_id = department_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.department_name
     *
     * @return the value of euc_user.department_name
     *
     * @mbg.generated
     */
    public String getDepartment_name() {
        return department_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.department_name
     *
     * @param department_name the value for euc_user.department_name
     *
     * @mbg.generated
     */
    public void setDepartment_name(String department_name) {
        this.department_name = department_name == null ? null : department_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.organization_id
     *
     * @return the value of euc_user.organization_id
     *
     * @mbg.generated
     */
    public Long getOrganization_id() {
        return organization_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.organization_id
     *
     * @param organization_id the value for euc_user.organization_id
     *
     * @mbg.generated
     */
    public void setOrganization_id(Long organization_id) {
        this.organization_id = organization_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.organization_name
     *
     * @return the value of euc_user.organization_name
     *
     * @mbg.generated
     */
    public String getOrganization_name() {
        return organization_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.organization_name
     *
     * @param organization_name the value for euc_user.organization_name
     *
     * @mbg.generated
     */
    public void setOrganization_name(String organization_name) {
        this.organization_name = organization_name == null ? null : organization_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.email
     *
     * @return the value of euc_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.email
     *
     * @param email the value for euc_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.address
     *
     * @return the value of euc_user.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.address
     *
     * @param address the value for euc_user.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.telephone
     *
     * @return the value of euc_user.telephone
     *
     * @mbg.generated
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.telephone
     *
     * @param telephone the value for euc_user.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.is_driver
     *
     * @return the value of euc_user.is_driver
     *
     * @mbg.generated
     */
    public String getIs_driver() {
        return is_driver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.is_driver
     *
     * @param is_driver the value for euc_user.is_driver
     *
     * @mbg.generated
     */
    public void setIs_driver(String is_driver) {
        this.is_driver = is_driver == null ? null : is_driver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.Identity_number
     *
     * @return the value of euc_user.Identity_number
     *
     * @mbg.generated
     */
    public String getIdentity_number() {
        return identity_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.Identity_number
     *
     * @param identity_number the value for euc_user.Identity_number
     *
     * @mbg.generated
     */
    public void setIdentity_number(String identity_number) {
        this.identity_number = identity_number == null ? null : identity_number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.dirver_num
     *
     * @return the value of euc_user.dirver_num
     *
     * @mbg.generated
     */
    public String getDirver_num() {
        return dirver_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.dirver_num
     *
     * @param dirver_num the value for euc_user.dirver_num
     *
     * @mbg.generated
     */
    public void setDirver_num(String dirver_num) {
        this.dirver_num = dirver_num == null ? null : dirver_num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.driving_end_time
     *
     * @return the value of euc_user.driving_end_time
     *
     * @mbg.generated
     */
    public Date getDriving_end_time() {
        return driving_end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.driving_end_time
     *
     * @param driving_end_time the value for euc_user.driving_end_time
     *
     * @mbg.generated
     */
    public void setDriving_end_time(Date driving_end_time) {
        this.driving_end_time = driving_end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.sex
     *
     * @return the value of euc_user.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.sex
     *
     * @param sex the value for euc_user.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.is_admin
     *
     * @return the value of euc_user.is_admin
     *
     * @mbg.generated
     */
    public Integer getIs_admin() {
        return is_admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.is_admin
     *
     * @param is_admin the value for euc_user.is_admin
     *
     * @mbg.generated
     */
    public void setIs_admin(Integer is_admin) {
        this.is_admin = is_admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.is_system_user
     *
     * @return the value of euc_user.is_system_user
     *
     * @mbg.generated
     */
    public Integer getIs_system_user() {
        return is_system_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.is_system_user
     *
     * @param is_system_user the value for euc_user.is_system_user
     *
     * @mbg.generated
     */
    public void setIs_system_user(Integer is_system_user) {
        this.is_system_user = is_system_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.owner_type
     *
     * @return the value of euc_user.owner_type
     *
     * @mbg.generated
     */
    public Integer getOwner_type() {
        return owner_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.owner_type
     *
     * @param owner_type the value for euc_user.owner_type
     *
     * @mbg.generated
     */
    public void setOwner_type(Integer owner_type) {
        this.owner_type = owner_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.is_platform
     *
     * @return the value of euc_user.is_platform
     *
     * @mbg.generated
     */
    public Integer getIs_platform() {
        return is_platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.is_platform
     *
     * @param is_platform the value for euc_user.is_platform
     *
     * @mbg.generated
     */
    public void setIs_platform(Integer is_platform) {
        this.is_platform = is_platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.company_name
     *
     * @return the value of euc_user.company_name
     *
     * @mbg.generated
     */
    public String getCompany_name() {
        return company_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.company_name
     *
     * @param company_name the value for euc_user.company_name
     *
     * @mbg.generated
     */
    public void setCompany_name(String company_name) {
        this.company_name = company_name == null ? null : company_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.position
     *
     * @return the value of euc_user.position
     *
     * @mbg.generated
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.position
     *
     * @param position the value for euc_user.position
     *
     * @mbg.generated
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.status
     *
     * @return the value of euc_user.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.status
     *
     * @param status the value for euc_user.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.created
     *
     * @return the value of euc_user.created
     *
     * @mbg.generated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.created
     *
     * @param created the value for euc_user.created
     *
     * @mbg.generated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.updated
     *
     * @return the value of euc_user.updated
     *
     * @mbg.generated
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.updated
     *
     * @param updated the value for euc_user.updated
     *
     * @mbg.generated
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.deleted
     *
     * @return the value of euc_user.deleted
     *
     * @mbg.generated
     */
    public Date getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.deleted
     *
     * @param deleted the value for euc_user.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Date deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        User other = (User) that;
        return (this.getUser_id() == null ? other.getUser_id() == null : this.getUser_id().equals(other.getUser_id()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getEnterprise_id() == null ? other.getEnterprise_id() == null : this.getEnterprise_id().equals(other.getEnterprise_id()))
            && (this.getAccount() == null ? other.getAccount() == null : this.getAccount().equals(other.getAccount()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getDepartment_id() == null ? other.getDepartment_id() == null : this.getDepartment_id().equals(other.getDepartment_id()))
            && (this.getDepartment_name() == null ? other.getDepartment_name() == null : this.getDepartment_name().equals(other.getDepartment_name()))
            && (this.getOrganization_id() == null ? other.getOrganization_id() == null : this.getOrganization_id().equals(other.getOrganization_id()))
            && (this.getOrganization_name() == null ? other.getOrganization_name() == null : this.getOrganization_name().equals(other.getOrganization_name()))
            && (this.getEmail() == null ? other.getEmail() == null : this.getEmail().equals(other.getEmail()))
            && (this.getAddress() == null ? other.getAddress() == null : this.getAddress().equals(other.getAddress()))
            && (this.getTelephone() == null ? other.getTelephone() == null : this.getTelephone().equals(other.getTelephone()))
            && (this.getIs_driver() == null ? other.getIs_driver() == null : this.getIs_driver().equals(other.getIs_driver()))
            && (this.getIdentity_number() == null ? other.getIdentity_number() == null : this.getIdentity_number().equals(other.getIdentity_number()))
            && (this.getDirver_num() == null ? other.getDirver_num() == null : this.getDirver_num().equals(other.getDirver_num()))
            && (this.getDriving_end_time() == null ? other.getDriving_end_time() == null : this.getDriving_end_time().equals(other.getDriving_end_time()))
            && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
            && (this.getIs_admin() == null ? other.getIs_admin() == null : this.getIs_admin().equals(other.getIs_admin()))
            && (this.getIs_system_user() == null ? other.getIs_system_user() == null : this.getIs_system_user().equals(other.getIs_system_user()))
            && (this.getOwner_type() == null ? other.getOwner_type() == null : this.getOwner_type().equals(other.getOwner_type()))
            && (this.getIs_platform() == null ? other.getIs_platform() == null : this.getIs_platform().equals(other.getIs_platform()))
            && (this.getCompany_name() == null ? other.getCompany_name() == null : this.getCompany_name().equals(other.getCompany_name()))
            && (this.getPosition() == null ? other.getPosition() == null : this.getPosition().equals(other.getPosition()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreated() == null ? other.getCreated() == null : this.getCreated().equals(other.getCreated()))
            && (this.getUpdated() == null ? other.getUpdated() == null : this.getUpdated().equals(other.getUpdated()))
            && (this.getDeleted() == null ? other.getDeleted() == null : this.getDeleted().equals(other.getDeleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUser_id() == null) ? 0 : getUser_id().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getEnterprise_id() == null) ? 0 : getEnterprise_id().hashCode());
        result = prime * result + ((getAccount() == null) ? 0 : getAccount().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getDepartment_id() == null) ? 0 : getDepartment_id().hashCode());
        result = prime * result + ((getDepartment_name() == null) ? 0 : getDepartment_name().hashCode());
        result = prime * result + ((getOrganization_id() == null) ? 0 : getOrganization_id().hashCode());
        result = prime * result + ((getOrganization_name() == null) ? 0 : getOrganization_name().hashCode());
        result = prime * result + ((getEmail() == null) ? 0 : getEmail().hashCode());
        result = prime * result + ((getAddress() == null) ? 0 : getAddress().hashCode());
        result = prime * result + ((getTelephone() == null) ? 0 : getTelephone().hashCode());
        result = prime * result + ((getIs_driver() == null) ? 0 : getIs_driver().hashCode());
        result = prime * result + ((getIdentity_number() == null) ? 0 : getIdentity_number().hashCode());
        result = prime * result + ((getDirver_num() == null) ? 0 : getDirver_num().hashCode());
        result = prime * result + ((getDriving_end_time() == null) ? 0 : getDriving_end_time().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getIs_admin() == null) ? 0 : getIs_admin().hashCode());
        result = prime * result + ((getIs_system_user() == null) ? 0 : getIs_system_user().hashCode());
        result = prime * result + ((getOwner_type() == null) ? 0 : getOwner_type().hashCode());
        result = prime * result + ((getIs_platform() == null) ? 0 : getIs_platform().hashCode());
        result = prime * result + ((getCompany_name() == null) ? 0 : getCompany_name().hashCode());
        result = prime * result + ((getPosition() == null) ? 0 : getPosition().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreated() == null) ? 0 : getCreated().hashCode());
        result = prime * result + ((getUpdated() == null) ? 0 : getUpdated().hashCode());
        result = prime * result + ((getDeleted() == null) ? 0 : getDeleted().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", user_id=").append(user_id);
        sb.append(", name=").append(name);
        sb.append(", enterprise_id=").append(enterprise_id);
        sb.append(", account=").append(account);
        sb.append(", password=").append(password);
        sb.append(", department_id=").append(department_id);
        sb.append(", department_name=").append(department_name);
        sb.append(", organization_id=").append(organization_id);
        sb.append(", organization_name=").append(organization_name);
        sb.append(", email=").append(email);
        sb.append(", address=").append(address);
        sb.append(", telephone=").append(telephone);
        sb.append(", is_driver=").append(is_driver);
        sb.append(", identity_number=").append(identity_number);
        sb.append(", dirver_num=").append(dirver_num);
        sb.append(", driving_end_time=").append(driving_end_time);
        sb.append(", sex=").append(sex);
        sb.append(", is_admin=").append(is_admin);
        sb.append(", is_system_user=").append(is_system_user);
        sb.append(", owner_type=").append(owner_type);
        sb.append(", is_platform=").append(is_platform);
        sb.append(", company_name=").append(company_name);
        sb.append(", position=").append(position);
        sb.append(", status=").append(status);
        sb.append(", created=").append(created);
        sb.append(", updated=").append(updated);
        sb.append(", deleted=").append(deleted);
        sb.append("]");
        return sb.toString();
    }
}