package com.om.blank.trade.model;

import java.util.Date;

public class user {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.user_id
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private Long user_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.name
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.enterprise_id
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private Long enterprise_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.account
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.password
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.department_id
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private Long department_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.department_name
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private String department_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.organization_id
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private Long organization_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.organization_name
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private String organization_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.email
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.address
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.telephone
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.is_driver
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private String is_driver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.Identity_number
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private String identity_number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.dirver_num
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private String dirver_num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.driving_end_time
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private Date driving_end_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.sex
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.is_admin
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private Integer is_admin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.is_system_user
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private Integer is_system_user;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.owner_type
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private Integer owner_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.is_platform
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private Integer is_platform;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.company_name
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private String company_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.position
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private Integer position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.status
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.created
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private Date created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.updated
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private Date updated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column euc_user.deleted
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    private Date deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.user_id
     *
     * @return the value of euc_user.user_id
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public Long getUser_id() {
        return user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.user_id
     *
     * @param user_id the value for euc_user.user_id
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.name
     *
     * @return the value of euc_user.name
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.name
     *
     * @param name the value for euc_user.name
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.enterprise_id
     *
     * @return the value of euc_user.enterprise_id
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public Long getEnterprise_id() {
        return enterprise_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.enterprise_id
     *
     * @param enterprise_id the value for euc_user.enterprise_id
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setEnterprise_id(Long enterprise_id) {
        this.enterprise_id = enterprise_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.account
     *
     * @return the value of euc_user.account
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.account
     *
     * @param account the value for euc_user.account
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setAccount(String account) {
        this.account = account == null ? null : account.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.password
     *
     * @return the value of euc_user.password
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.password
     *
     * @param password the value for euc_user.password
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.department_id
     *
     * @return the value of euc_user.department_id
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public Long getDepartment_id() {
        return department_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.department_id
     *
     * @param department_id the value for euc_user.department_id
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setDepartment_id(Long department_id) {
        this.department_id = department_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.department_name
     *
     * @return the value of euc_user.department_name
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public String getDepartment_name() {
        return department_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.department_name
     *
     * @param department_name the value for euc_user.department_name
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setDepartment_name(String department_name) {
        this.department_name = department_name == null ? null : department_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.organization_id
     *
     * @return the value of euc_user.organization_id
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public Long getOrganization_id() {
        return organization_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.organization_id
     *
     * @param organization_id the value for euc_user.organization_id
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setOrganization_id(Long organization_id) {
        this.organization_id = organization_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.organization_name
     *
     * @return the value of euc_user.organization_name
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public String getOrganization_name() {
        return organization_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.organization_name
     *
     * @param organization_name the value for euc_user.organization_name
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setOrganization_name(String organization_name) {
        this.organization_name = organization_name == null ? null : organization_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.email
     *
     * @return the value of euc_user.email
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.email
     *
     * @param email the value for euc_user.email
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.address
     *
     * @return the value of euc_user.address
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.address
     *
     * @param address the value for euc_user.address
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.telephone
     *
     * @return the value of euc_user.telephone
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.telephone
     *
     * @param telephone the value for euc_user.telephone
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.is_driver
     *
     * @return the value of euc_user.is_driver
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public String getIs_driver() {
        return is_driver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.is_driver
     *
     * @param is_driver the value for euc_user.is_driver
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setIs_driver(String is_driver) {
        this.is_driver = is_driver == null ? null : is_driver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.Identity_number
     *
     * @return the value of euc_user.Identity_number
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public String getIdentity_number() {
        return identity_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.Identity_number
     *
     * @param identity_number the value for euc_user.Identity_number
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setIdentity_number(String identity_number) {
        this.identity_number = identity_number == null ? null : identity_number.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.dirver_num
     *
     * @return the value of euc_user.dirver_num
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public String getDirver_num() {
        return dirver_num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.dirver_num
     *
     * @param dirver_num the value for euc_user.dirver_num
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setDirver_num(String dirver_num) {
        this.dirver_num = dirver_num == null ? null : dirver_num.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.driving_end_time
     *
     * @return the value of euc_user.driving_end_time
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public Date getDriving_end_time() {
        return driving_end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.driving_end_time
     *
     * @param driving_end_time the value for euc_user.driving_end_time
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setDriving_end_time(Date driving_end_time) {
        this.driving_end_time = driving_end_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.sex
     *
     * @return the value of euc_user.sex
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.sex
     *
     * @param sex the value for euc_user.sex
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.is_admin
     *
     * @return the value of euc_user.is_admin
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public Integer getIs_admin() {
        return is_admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.is_admin
     *
     * @param is_admin the value for euc_user.is_admin
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setIs_admin(Integer is_admin) {
        this.is_admin = is_admin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.is_system_user
     *
     * @return the value of euc_user.is_system_user
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public Integer getIs_system_user() {
        return is_system_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.is_system_user
     *
     * @param is_system_user the value for euc_user.is_system_user
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setIs_system_user(Integer is_system_user) {
        this.is_system_user = is_system_user;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.owner_type
     *
     * @return the value of euc_user.owner_type
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public Integer getOwner_type() {
        return owner_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.owner_type
     *
     * @param owner_type the value for euc_user.owner_type
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setOwner_type(Integer owner_type) {
        this.owner_type = owner_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.is_platform
     *
     * @return the value of euc_user.is_platform
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public Integer getIs_platform() {
        return is_platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.is_platform
     *
     * @param is_platform the value for euc_user.is_platform
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setIs_platform(Integer is_platform) {
        this.is_platform = is_platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.company_name
     *
     * @return the value of euc_user.company_name
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public String getCompany_name() {
        return company_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.company_name
     *
     * @param company_name the value for euc_user.company_name
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setCompany_name(String company_name) {
        this.company_name = company_name == null ? null : company_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.position
     *
     * @return the value of euc_user.position
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.position
     *
     * @param position the value for euc_user.position
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.status
     *
     * @return the value of euc_user.status
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.status
     *
     * @param status the value for euc_user.status
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.created
     *
     * @return the value of euc_user.created
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.created
     *
     * @param created the value for euc_user.created
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.updated
     *
     * @return the value of euc_user.updated
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public Date getUpdated() {
        return updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.updated
     *
     * @param updated the value for euc_user.updated
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column euc_user.deleted
     *
     * @return the value of euc_user.deleted
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public Date getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column euc_user.deleted
     *
     * @param deleted the value for euc_user.deleted
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    public void setDeleted(Date deleted) {
        this.deleted = deleted;
    }
}