package com.om.blank.trade.mapper;

import com.om.blank.trade.model.user;
import com.om.blank.trade.model.userExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface userMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    long countByExample(userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    int deleteByExample(userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    int deleteByPrimaryKey(Long user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    int insert(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    int insertSelective(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    List<user> selectByExample(userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    user selectByPrimaryKey(Long user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") user record, @Param("example") userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    int updateByExample(@Param("record") user record, @Param("example") userExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    int updateByPrimaryKeySelective(user record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated Mon Jan 15 21:59:55 CST 2018
     */
    int updateByPrimaryKey(user record);
}