package com.om.blank.trade.mybatis.mapper;

import com.om.blank.trade.mybatis.base.BaseExample;
import com.om.blank.trade.mybatis.base.BaseMapper;
import com.om.blank.trade.mybatis.model.User;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated
     */
    long countByExample(BaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated
     */
    int deleteByExample(BaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated
     */
    List<User> selectByExample(BaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated
     */
    User selectByPrimaryKey(Long user_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") BaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") User record, @Param("example") BaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table euc_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(User record);
}